### ISSUE TITLE
Please add support for 9060XT (GFX1200)

### ISSUE THREAD

**Issue by dstsmallbird** [likelovewant/ollama-for-amd#103]
Could you please add the 9060XT to ollama-for-amd?

Thx :)

**Comment by Algorithman** [comment]
I just did, but still, my 9070XT is not recognized.
Copied all over (except the `ggml-hip.dll` which is not present in hip6.4 SDK.

Edit: nevermind.
Just don't set `HSA_OVERRIDE_GFX_VERSION`, then it works just fine. Thanks a lot

**Comment by likelovewant** [comment]
> I just did, but still, my 9070XT is not recognized. Copied all over (except the `ggml-hip.dll` which is not present in hip6.4 SDK.
> 
> Edit: nevermind. Just don't set `HSA_OVERRIDE_GFX_VERSION`, then it works just fine. Thanks a lot
cool ,  `HSA_OVERRIDE_GFX_VERSION` dont works on windows .however it's works for som arches due to mismatch of drivers.

**Comment by qixidao** [comment]
我也是9060xt 16G,从C:\Program Files\AMD\ROCm\6.4\bin\rocblas\library拷贝library到ollama的目录，确实能识别到9060xt，但是不管运行什么模型，都不会加载到GPU, 我下的是最新版的ROCm

**Comment by likelovewant** [comment]
Rocblas.dll

**Comment by qixidao** [comment]
> Rocblas.dll

是的，我并没有漏掉这个，从C:\Program Files\AMD\ROCm\6.4\bin复制Rocblas.dll到ollama的指定目录，但是加载任何模型都是不使用GPU
