### ISSUE TITLE
GFX1152(860M) 无法生成内容

### ISSUE THREAD

**Issue by crackerfly** [likelovewant/ollama-for-amd#106]
### What is the issue?

显卡 GFX1152(860M) 
版本 https://github.com/likelovewant/ollama-for-amd/releases/tag/v0.12.3
驱动 25.9.1

输入问题后无内容输出，烦请帮忙看看。。 感谢大佬

### Relevant log output

```shell
日志如下：

time=2025-10-28T21:12:47.060+08:00 level=INFO source=routes.go:1475 msg="server config" env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES:0 HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_CONTEXT_LENGTH:4096 OLLAMA_DEBUG:INFO OLLAMA_FLASH_ATTENTION:true OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:20m0s OLLAMA_KV_CACHE_TYPE: OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:C:\\Program Files\\StarSoftComm\\ZhanAI\\Ollama\\Models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NEW_ENGINE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:1 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://* vscode-file://*] OLLAMA_REMOTES:[ollama.com] OLLAMA_SCHED_SPREAD:false ROCR_VISIBLE_DEVICES:]"
time=2025-10-28T21:12:47.071+08:00 level=INFO source=images.go:518 msg="total blobs: 11"
time=2025-10-28T21:12:47.073+08:00 level=INFO source=images.go:525 msg="total unused blobs removed: 0"
time=2025-10-28T21:12:47.084+08:00 level=INFO source=routes.go:1528 msg="Listening on 127.0.0.1:11434 (version 0.12.3)"
time=2025-10-28T21:12:47.084+08:00 level=INFO source=gpu.go:217 msg="looking for compatible GPUs"
time=2025-10-28T21:12:47.085+08:00 level=INFO source=gpu_windows.go:167 msg=packages count=1
time=2025-10-28T21:12:47.085+08:00 level=INFO source=gpu_windows.go:183 msg="efficiency cores detected" maxEfficiencyClass=1
time=2025-10-28T21:12:47.085+08:00 level=INFO source=gpu_windows.go:214 msg="" package=0 cores=8 efficiency=4 threads=16
time=2025-10-28T21:12:48.577+08:00 level=INFO source=types.go:131 msg="inference compute" id=0 library=rocm variant="" compute=gfx1152 driver=6.4 name="AMD Radeon(TM) 860M Graphics" total="24.2 GiB" available="24.1 GiB"
[GIN] 2025/10/28 - 21:14:18 | 200 |            0s |       127.0.0.1 | HEAD     "/"
[GIN] 2025/10/28 - 21:14:18 | 200 |      2.4105ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2025/10/28 - 21:15:31 | 200 |            0s |       127.0.0.1 | HEAD     "/"
[GIN] 2025/10/28 - 21:15:31 | 200 |    124.7148ms |       127.0.0.1 | POST     "/api/show"
time=2025-10-28T21:15:32.599+08:00 level=INFO source=sched.go:192 msg="one or more GPUs detected that are unable to accurately report free memory - disabling default concurrency"
time=2025-10-28T21:15:35.185+08:00 level=INFO source=server.go:217 msg="enabling flash attention"
time=2025-10-28T21:15:35.196+08:00 level=INFO source=server.go:399 msg="starting runner" cmd="C:\\Program Files\\StarSoftComm\\ZhanAI\\Ollama\\Apps\\AMD\\ollama.exe runner --ollama-engine --model C:\\Program Files\\StarSoftComm\\ZhanAI\\Ollama\\Models\\blobs\\sha256-58574f2e94b99fb9e4391408b57e5aeaaaec10f6384e9a699fc2cb43a5c8eabf --port 64058"
time=2025-10-28T21:15:35.203+08:00 level=INFO source=server.go:672 msg="loading model" "model layers"=49 requested=-1
time=2025-10-28T21:15:35.253+08:00 level=INFO source=runner.go:1252 msg="starting ollama engine"
time=2025-10-28T21:15:35.262+08:00 level=INFO source=runner.go:1287 msg="Server listening on 127.0.0.1:64058"
time=2025-10-28T21:15:37.771+08:00 level=INFO source=server.go:678 msg="system memory" total="63.3 GiB" free="51.6 GiB" free_swap="54.7 GiB"
time=2025-10-28T21:15:37.771+08:00 level=INFO source=server.go:686 msg="gpu memory" id=0 available="23.5 GiB" free="23.9 GiB" minimum="457.0 MiB" overhead="0 B"
time=2025-10-28T21:15:37.774+08:00 level=INFO source=runner.go:1171 msg=load request="{Operation:fit LoraPath:[] Parallel:1 BatchSize:512 FlashAttention:true KvSize:4096 KvCacheType: NumThreads:4 GPULayers:49[ID:0 Layers:49(0..48)] MultiUserCache:false ProjectorPath: MainGPU:0 UseMmap:false}"
time=2025-10-28T21:15:37.795+08:00 level=INFO source=ggml.go:131 msg="" architecture=qwen3moe file_type=Q4_K_M name="Qwen3 30B A3B Thinking 2507" description="" num_tensors=579 num_key_values=33
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon(TM) 860M Graphics, gfx1152 (0x1152), VMM: no, Wave Size: 32, ID: 0
load_backend: loaded ROCm backend from C:\Program Files\StarSoftComm\ZhanAI\Ollama\Apps\AMD\lib\ollama\ggml-hip.dll
load_backend: loaded CPU backend from C:\Program Files\StarSoftComm\ZhanAI\Ollama\Apps\AMD\lib\ollama\ggml-cpu-icelake.dll
time=2025-10-28T21:15:39.345+08:00 level=INFO source=ggml.go:104 msg=system CPU.0.SSE3=1 CPU.0.SSSE3=1 CPU.0.AVX=1 CPU.0.AVX2=1 CPU.0.F16C=1 CPU.0.FMA=1 CPU.0.BMI2=1 CPU.0.AVX512=1 CPU.0.AVX512_VBMI=1 CPU.0.AVX512_VNNI=1 CPU.0.LLAMAFILE=1 CPU.1.LLAMAFILE=1 ROCm.0.NO_VMM=1 ROCm.0.NO_PEER_COPY=1 ROCm.0.PEER_MAX_BATCH_SIZE=128 compiler=cgo(clang)
time=2025-10-28T21:15:43.003+08:00 level=INFO source=runner.go:1171 msg=load request="{Operation:alloc LoraPath:[] Parallel:1 BatchSize:512 FlashAttention:true KvSize:4096 KvCacheType: NumThreads:4 GPULayers:49[ID:0 Layers:49(0..48)] MultiUserCache:false ProjectorPath: MainGPU:0 UseMmap:false}"
time=2025-10-28T21:15:46.548+08:00 level=INFO source=runner.go:1171 msg=load request="{Operation:commit LoraPath:[] Parallel:1 BatchSize:512 FlashAttention:true KvSize:4096 KvCacheType: NumThreads:4 GPULayers:49[ID:0 Layers:49(0..48)] MultiUserCache:false ProjectorPath: MainGPU:0 UseMmap:false}"
time=2025-10-28T21:15:46.548+08:00 level=INFO source=ggml.go:487 msg="offloading 48 repeating layers to GPU"
time=2025-10-28T21:15:46.548+08:00 level=INFO source=ggml.go:493 msg="offloading output layer to GPU"
time=2025-10-28T21:15:46.548+08:00 level=INFO source=ggml.go:498 msg="offloaded 49/49 layers to GPU"
time=2025-10-28T21:15:46.549+08:00 level=INFO source=backend.go:310 msg="model weights" device=ROCm0 size="17.1 GiB"
time=2025-10-28T21:15:46.552+08:00 level=INFO source=backend.go:315 msg="model weights" device=CPU size="166.9 MiB"
time=2025-10-28T21:15:46.552+08:00 level=INFO source=backend.go:321 msg="kv cache" device=ROCm0 size="384.0 MiB"
time=2025-10-28T21:15:46.552+08:00 level=INFO source=backend.go:332 msg="compute graph" device=ROCm0 size="88.0 MiB"
time=2025-10-28T21:15:46.552+08:00 level=INFO source=backend.go:337 msg="compute graph" device=CPU size="4.0 MiB"
time=2025-10-28T21:15:46.553+08:00 level=INFO source=backend.go:342 msg="total memory" size="17.7 GiB"
time=2025-10-28T21:15:46.553+08:00 level=INFO source=sched.go:470 msg="loaded runners" count=1
time=2025-10-28T21:15:46.554+08:00 level=INFO source=server.go:1251 msg="waiting for llama runner to start responding"
time=2025-10-28T21:15:46.554+08:00 level=INFO source=server.go:1285 msg="waiting for server to become available" status="llm server loading model"
time=2025-10-28T21:15:57.964+08:00 level=INFO source=server.go:1289 msg="llama runner started in 22.77 seconds"
[GIN] 2025/10/28 - 21:15:57 | 200 |   26.2940459s |       127.0.0.1 | POST     "/api/generate"
panic: failed to sample token: sample: logits sum to NaN, check model output

goroutine 12 [running]:
github.com/ollama/ollama/runner/ollamarunner.(*Server).run(0xc0005d63c0, {0x7ff76aa13180, 0xc00012c410})
        C:/a/ollama/ollama/runner/ollamarunner/runner.go:416 +0x35c
created by github.com/ollama/ollama/runner/ollamarunner.Execute in goroutine 1
        C:/a/ollama/ollama/runner/ollamarunner/runner.go:1266 +0x505
```

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.12.3

**Comment by likelovewant** [comment]
多分配专用显存空间

**Comment by crackerfly** [comment]
> 多分配专用显存空间

感谢大佬回复，经测试基于官方的0.12.6版本，替换您的rocm-gfx1152组件后可以正常运行，再次感谢～
