### ISSUE TITLE
最新的0.3.14-0-gc692dfd版本不支持老显卡了，0.3.13就没问题

### ISSUE THREAD

**Issue by qixidao** [likelovewant/ollama-for-amd#24]
### What is the issue?

![QQ图片20241022121458](https://github.com/user-attachments/assets/439e6dfe-398d-4b53-80cf-20bcc77f3c18)
图片上面部分是0.3.13的运行日志，下部分是0.3.14的运行日志，其他条件都没变，显卡是5700xt

### OS

Windows

### GPU

AMD

### CPU

Intel

### Ollama version

0.3.14

**Comment by pc-v2** [comment]
same here 
```
2024/10/22 11:33:28 routes.go:1170: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION:gfx1030 HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:C:\\Users\\neko\\.ollama\\models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://*] OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-10-22T11:33:28.577+07:00 level=INFO source=images.go:754 msg="total blobs: 34"
time=2024-10-22T11:33:28.582+07:00 level=INFO source=images.go:761 msg="total unused blobs removed: 0"
time=2024-10-22T11:33:28.586+07:00 level=INFO source=routes.go:1217 msg="Listening on 127.0.0.1:11434 (version 0.3.14-0-gc692dfd)"
time=2024-10-22T11:33:28.586+07:00 level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[cpu cpu_avx cpu_avx2 rocm_v6.1]"
time=2024-10-22T11:33:28.586+07:00 level=INFO source=gpu.go:221 msg="looking for compatible GPUs"
time=2024-10-22T11:33:28.587+07:00 level=INFO source=gpu_windows.go:167 msg=packages count=1
time=2024-10-22T11:33:28.587+07:00 level=INFO source=gpu_windows.go:214 msg="" package=0 cores=6 efficiency=0 threads=12
time=2024-10-22T11:33:28.636+07:00 level=INFO source=amd_windows.go:70 msg="skipping rocm gfx compatibility check" HSA_OVERRIDE_GFX_VERSION=gfx1030
time=2024-10-22T11:33:29.183+07:00 level=WARN source=amd_windows.go:138 msg="amdgpu is not supported (supported types:[])" gpu_type=gfx1031 gpu=0 library=C:\Users\neko\AppData\Local\Programs\Ollama\lib\ollama
time=2024-10-22T11:33:29.186+07:00 level=INFO source=gpu.go:384 msg="no compatible GPUs were discovered"
time=2024-10-22T11:33:29.186+07:00 level=INFO source=types.go:123 msg="inference compute" id=0 library=cpu variant=avx2 compute="" driver=0.0 name="" total="31.9 GiB" available="25.3 GiB"
```

Already patch the library with rocm.gfx1031.for.hip.sdk.6.1.2

**Comment by likelovewant** [comment]
try remove the set in your previous system enviroment set , it's not correct.

`HSA_OVERRIDE_GFX_VERSION=gfx9.0.12` @qixidao 
`HSA_OVERRIDE_GFX_VERSION=gfx1030` @pc-v2

**Comment by qixidao** [comment]
`2024/10/22 16:12:48 routes.go:1170: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:D:\\300\\AMDROCm\\models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://*] OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-10-22T16:12:48.401+08:00 level=INFO source=images.go:754 msg="total blobs: 48"
time=2024-10-22T16:12:48.407+08:00 level=INFO source=images.go:761 msg="total unused blobs removed: 0"
time=2024-10-22T16:12:48.410+08:00 level=INFO source=routes.go:1217 msg="Listening on [::]:11434 (version 0.3.14-0-gc692dfd)"
time=2024-10-22T16:12:48.413+08:00 level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[cpu cpu_avx cpu_avx2 rocm_v6.1]"
time=2024-10-22T16:12:48.413+08:00 level=INFO source=gpu.go:221 msg="looking for compatible GPUs"
time=2024-10-22T16:12:48.413+08:00 level=INFO source=gpu_windows.go:167 msg=packages count=1
time=2024-10-22T16:12:48.413+08:00 level=INFO source=gpu_windows.go:214 msg="" package=0 cores=12 efficiency=0 threads=12
time=2024-10-22T16:12:49.344+08:00 level=WARN source=amd_windows.go:138 msg="amdgpu is not supported (supported types:[gfx1103])" gpu_type=gfx1010:xnack- gpu=0 library=C:\Users\saki\AppData\Local\Programs\Ollama\lib\ollama
time=2024-10-22T16:12:49.347+08:00 level=INFO source=gpu.go:384 msg="no compatible GPUs were discovered"
time=2024-10-22T16:12:49.347+08:00 level=INFO source=types.go:123 msg="inference compute" id=0 library=cpu variant=avx2 compute="" driver=0.0 name="" total="15.9 GiB" available="10.9 GiB"
`

> try remove the set in your previous system enviroment set , it's not correct.
> 
> `HSA_OVERRIDE_GFX_VERSION=gfx9.0.12` @qixidao `HSA_OVERRIDE_GFX_VERSION=gfx1030` @pc-v2

Still the Same。

**Comment by likelovewant** [comment]
> `2024/10/22 16:12:48 routes.go:1170: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:D:\\300\\AMDROCm\\models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://*] OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
> 
> time=2024-10-22T16:12:48.401+08:00 level=INFO source=images.go:754 msg="total blobs: 48"
> 
> time=2024-10-22T16:12:48.407+08:00 level=INFO source=images.go:761 msg="total unused blobs removed: 0"
> 
> time=2024-10-22T16:12:48.410+08:00 level=INFO source=routes.go:1217 msg="Listening on [::]:11434 (version 0.3.14-0-gc692dfd)"
> 
> time=2024-10-22T16:12:48.413+08:00 level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[cpu cpu_avx cpu_avx2 rocm_v6.1]"
> 
> time=2024-10-22T16:12:48.413+08:00 level=INFO source=gpu.go:221 msg="looking for compatible GPUs"
> 
> time=2024-10-22T16:12:48.413+08:00 level=INFO source=gpu_windows.go:167 msg=packages count=1
> 
> time=2024-10-22T16:12:48.413+08:00 level=INFO source=gpu_windows.go:214 msg="" package=0 cores=12 efficiency=0 threads=12
> 
> time=2024-10-22T16:12:49.344+08:00 level=WARN source=amd_windows.go:138 msg="amdgpu is not supported (supported types:[gfx1103])" gpu_type=gfx1010:xnack- gpu=0 library=C:\Users\saki\AppData\Local\Programs\Ollama\lib\ollama
> 
> time=2024-10-22T16:12:49.347+08:00 level=INFO source=gpu.go:384 msg="no compatible GPUs were discovered"
> 
> time=2024-10-22T16:12:49.347+08:00 level=INFO source=types.go:123 msg="inference compute" id=0 library=cpu variant=avx2 compute="" driver=0.0 name="" total="15.9 GiB" available="10.9 GiB"
> 
> `
> 
> 
> 
> > try remove the set in your previous system enviroment set , it's not correct.
> 
> > 
> 
> > `HSA_OVERRIDE_GFX_VERSION=gfx9.0.12` @qixidao `HSA_OVERRIDE_GFX_VERSION=gfx1030` @pc-v2
> 
> 
> 
> Still the Same。

please follow the wiki guide to replace the rocm lib for gfx1010:xnack,with both rocblas.dll and library.

**Comment by pc-v2** [comment]
```
2024/10/22 21:32:31 routes.go:1170: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:C:\\Users\\neko\\.ollama\\models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://*] OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-10-22T21:32:31.445+07:00 level=INFO source=images.go:754 msg="total blobs: 34"
time=2024-10-22T21:32:31.449+07:00 level=INFO source=images.go:761 msg="total unused blobs removed: 0"
time=2024-10-22T21:32:31.452+07:00 level=INFO source=routes.go:1217 msg="Listening on 127.0.0.1:11434 (version 0.3.14-0-gc692dfd)"
time=2024-10-22T21:32:31.453+07:00 level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[cpu cpu_avx cpu_avx2 rocm_v6.1]"
time=2024-10-22T21:32:31.453+07:00 level=INFO source=gpu.go:221 msg="looking for compatible GPUs"
time=2024-10-22T21:32:31.453+07:00 level=INFO source=gpu_windows.go:167 msg=packages count=1
time=2024-10-22T21:32:31.453+07:00 level=INFO source=gpu_windows.go:214 msg="" package=0 cores=6 efficiency=0 threads=12
time=2024-10-22T21:32:32.223+07:00 level=INFO source=types.go:123 msg="inference compute" id=0 library=rocm variant="" compute=gfx1031 driver=6.2 name="AMD Radeon RX 6700 XT" total="12.0 GiB" available="11.8 GiB"
```

now it runs :) did something changed? it was running in previous ollama for amd (v0.3.13) with hsa override

**Comment by likelovewant** [comment]
> ```
> 2024/10/22 21:32:31 routes.go:1170: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:C:\\Users\\neko\\.ollama\\models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://*] OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
> time=2024-10-22T21:32:31.445+07:00 level=INFO source=images.go:754 msg="total blobs: 34"
> time=2024-10-22T21:32:31.449+07:00 level=INFO source=images.go:761 msg="total unused blobs removed: 0"
> time=2024-10-22T21:32:31.452+07:00 level=INFO source=routes.go:1217 msg="Listening on 127.0.0.1:11434 (version 0.3.14-0-gc692dfd)"
> time=2024-10-22T21:32:31.453+07:00 level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[cpu cpu_avx cpu_avx2 rocm_v6.1]"
> time=2024-10-22T21:32:31.453+07:00 level=INFO source=gpu.go:221 msg="looking for compatible GPUs"
> time=2024-10-22T21:32:31.453+07:00 level=INFO source=gpu_windows.go:167 msg=packages count=1
> time=2024-10-22T21:32:31.453+07:00 level=INFO source=gpu_windows.go:214 msg="" package=0 cores=6 efficiency=0 threads=12
> time=2024-10-22T21:32:32.223+07:00 level=INFO source=types.go:123 msg="inference compute" id=0 library=rocm variant="" compute=gfx1031 driver=6.2 name="AMD Radeon RX 6700 XT" total="12.0 GiB" available="11.8 GiB"
> ```
> 
> now it runs :) did something changed? it was running in previous ollama for amd (v0.3.13) with hsa override

The previous override maybe never works ,has update the code  .https://github.com/likelovewant/ollama-for-amd/blob/main/discover/amd_windows.go

**Comment by qixidao** [comment]
> > `2024/10/22 16:12:48 routes.go:1170: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:D:\300\AMDROCm\models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://*] OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
> > time=2024-10-22T16:12:48.401+08:00 level=INFO source=images.go:754 msg="total blobs: 48"
> > time=2024-10-22T16:12:48.407+08:00 level=INFO source=images.go:761 msg="total unused blobs removed: 0"
> > time=2024-10-22T16:12:48.410+08:00 level=INFO source=routes.go:1217 msg="Listening on [::]:11434 (version 0.3.14-0-gc692dfd)"
> > time=2024-10-22T16:12:48.413+08:00 level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[cpu cpu_avx cpu_avx2 rocm_v6.1]"
> > time=2024-10-22T16:12:48.413+08:00 level=INFO source=gpu.go:221 msg="looking for compatible GPUs"
> > time=2024-10-22T16:12:48.413+08:00 level=INFO source=gpu_windows.go:167 msg=packages count=1
> > time=2024-10-22T16:12:48.413+08:00 level=INFO source=gpu_windows.go:214 msg="" package=0 cores=12 efficiency=0 threads=12
> > time=2024-10-22T16:12:49.344+08:00 level=WARN source=amd_windows.go:138 msg="amdgpu is not supported (supported types:[gfx1103])" gpu_type=gfx1010:xnack- gpu=0 library=C:\Users\saki\AppData\Local\Programs\Ollama\lib\ollama
> > time=2024-10-22T16:12:49.347+08:00 level=INFO source=gpu.go:384 msg="no compatible GPUs were discovered"
> > time=2024-10-22T16:12:49.347+08:00 level=INFO source=types.go:123 msg="inference compute" id=0 library=cpu variant=avx2 compute="" driver=0.0 name="" total="15.9 GiB" available="10.9 GiB"
> > `
> > > try remove the set in your previous system enviroment set , it's not correct.
> > 
> > 
> > > 
> > 
> > 
> > > `HSA_OVERRIDE_GFX_VERSION=gfx9.0.12` @qixidao `HSA_OVERRIDE_GFX_VERSION=gfx1030` @pc-v2
> > 
> > 
> > Still the Same。
> 
> please follow the wiki guide to replace the rocm lib for gfx1010:xnack,with both rocblas.dll and library.

What is the specific operation method，
I have read the wiki many times，
All configurations remain unchanged. 
Repeat installation many times
There is no problem with 3.13, but it is not supported on 3.14，
My graphics card is AMD 5700XT,

**Comment by qixidao** [comment]
@likelovewant Thanks a lot for the help! It was a bit tricky since I was stuck on an old method, but your approach solved my issue
