### ISSUE TITLE
gfx803 with HIP SDK 6.1.2 not working

### ISSUE THREAD

**Issue by zuli12-dev** [likelovewant/ollama-for-amd#25]
### What is the issue?

Hi!

Many thanks for this amazing project, as i am stuck with getting this even to run in Linux i wanted to give it a try in windows with this repository.

I am running Win11 as a Proxmox Maschine with a valid PCI Passthrough.

I followed the Wiki exactly, and installed all dependencies.

HIP SDK 6.1.2
gfx803 (Radeon RX580 8Gb)

I can confirm the gpu was detected in versions 0.3.2 and i think also 0.3.4
I tried every release on the page, used the .exe and also the binary form of it, replaced the dll's and gave it a try.
the gpu never get's detected now since then, in the old versions i got errors about rocm entrypoints not found in dll, but i assume a lot has changed and thus wanted to use a newer release.

So my steps are:

download and install hip 6.1.2
download the needed rocm.gfx803.optic.vega10.logic.hip.sdk.6.1.2.7z
replace the files in C:\Program Files\AMD....

download the latest release (7zip) - extract
try to run ollama.exe from the downloaded release ( with the shipped dll's) - GPU not detected
replace the rocblas and library of the release with the ones from rocm.gfx803.optic.vega10.logic.hip.sdk.6.1.2.7z - GPU not detected

The same happens with the native installer and also when using the gui installer.

I am kind of stuck here, seems i am missing something ? (Note i did not build as it is not working yet)

Any help would be much much appreciated - Thanks a lot! 

### OS

Windows

### GPU

AMD

### CPU

Intel

### Ollama version

0.3.14

**Comment by zuli12-dev** [comment]
After updating from Ollama version 3.2 to 3.14, the GPU is no longer detected properly. Both versions use the same ROCm libraries (rocm.gfx803.optic.vega10.logic.hip.sdk.6.1.2).

Logs with Version 3.2
```
PS C:\Users\mario> C:\Users\mario\Downloads\ollama-windows-amd64_0.3.2\ollama.exe serve
2024/10/25 14:47:46 routes.go:1108: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: ...]"
time=2024-10-25T14:47:46.201+02:00 level=INFO source=images.go:781 msg="total blobs: 5"
time=2024-10-25T14:47:46.203+02:00 level=INFO source=images.go:788 msg="total unused blobs removed: 0"
time=2024-10-25T14:47:46.203+02:00 level=INFO source=routes.go:1155 msg="Listening on 127.0.0.1:11434 (version 0.3.2-0-g63a5f50)"
time=2024-10-25T14:47:46.204+02:00 level=INFO source=payload.go:44 msg="Dynamic LLM libraries [cpu cpu_avx cpu_avx2 rocm_v5.7]"
time=2024-10-25T14:47:46.204+02:00 level=INFO source=gpu.go:205 msg="looking for compatible GPUs"
time=2024-10-25T14:47:46.658+02:00 level=INFO source=types.go:105 msg="inference compute" id=0 library=rocm compute=gfx803 driver=0.3 name="Radeon RX 580 Series" total="8.0 GiB" available="7.9 GiB"
[GIN] 2024/10/25 - 14:48:09 | 200 |            0s |       127.0.0.1 | HEAD     "/"
[GIN] 2024/10/25 - 14:48:09 | 200 |     43.7715ms |       127.0.0.1 | POST     "/api/show"
time=2024-10-25T14:48:09.602+02:00 level=INFO source=sched.go:185 msg="one or more GPUs detected that are unable to accurately report free memory - disabling default concurrency"
time=2024-10-25T14:48:09.607+02:00 level=INFO source=sched.go:710 msg="new model will fit in available VRAM in single GPU, loading" model=C:\Users\mario\.ollama\models\blobs\sha256-eb2c714d40d4b35ba4b8ee98475a06d51d8080a17d2d2a75a23665985c739b94 gpu=0 parallel=4 available=8455716864 required="895.2 MiB"
time=2024-10-25T14:48:09.614+02:00 level=INFO source=server.go:384 msg="starting llama server" cmd="C:\Users\mario\Downloads\ollama-windows-amd64_0.3.2\ollama_runners\rocm_v5.7\ollama_llama_server.exe ..."
time=2024-10-25T14:48:09.678+02:00 level=INFO source=sched.go:445 msg="loaded runners" count=1
time=2024-10-25T14:48:09.678+02:00 level=INFO source=server.go:584 msg="waiting for llama runner to start responding"
time=2024-10-25T14:48:09.681+02:00 level=INFO source=server.go:618 msg="waiting for server to become available" status="llm server error"
````

Logs with Version 3.14
```
PS C:\Users\mario> C:\Users\mario\Downloads\ollama-windows-amd64\ollama.exe --version
Warning: could not connect to a running Ollama instance
Warning: client version is 0.3.14-0-gc692dfd

PS C:\Users\mario> C:\Users\mario\Downloads\ollama-windows-amd64\ollama.exe serve
2024/10/25 14:55:52 routes.go:1170: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: ...]"
time=2024-10-25T14:55:52.303+02:00 level=INFO source=images.go:754 msg="total blobs: 5"
time=2024-10-25T14:55:52.304+02:00 level=INFO source=images.go:761 msg="total unused blobs removed: 0"
time=2024-10-25T14:55:52.305+02:00 level=INFO source=routes.go:1217 msg="Listening on 127.0.0.1:11434 (version 0.3.14-0-gc692dfd)"
time=2024-10-25T14:55:52.305+02:00 level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[cpu cpu_avx cpu_avx2 rocm_v6.1]"
time=2024-10-25T14:55:52.305+02:00 level=INFO source=gpu.go:221 msg="looking for compatible GPUs"
time=2024-10-25T14:55:52.305+02:00 level=INFO source=gpu_windows.go:167 msg=packages count=1
time=2024-10-25T14:55:52.305+02:00 level=INFO source=gpu_windows.go:214 msg="" package=0 cores=12 efficiency=0 threads=12
time=2024-10-25T14:55:52.311+02:00 level=INFO source=gpu.go:384 msg="no compatible GPUs were discovered"
time=2024-10-25T14:55:52.312+02:00 level=INFO source=types.go:123 msg="inference compute" id=0 library=cpu variant=avx2 compute="" driver=0.0 name="" total="39.1 GiB" available="32.8 GiB"
```


In Version 3.2, the GPU (Radeon RX 580 Series) is detected and available, with specific memory details.
In Version 3.14, the GPU is no longer detected (msg="no compatible GPUs were discovered"), despite using the same ROCm libraries.

**Comment by likelovewant** [comment]
1. need latest drivers otherwise can not detected if you had replace the libs.

2. the earlier version need rocmlibs for rocm5.7 should work properly while the latest need rocm 6.1.2 .but not received any feedback or can not use since update to rocm6.1. And version for rocm5.7 release in one of the last two releases . Please check it out

**Comment by zuli12-dev** [comment]
thanks for the response @likelovewant.
Yes i used the latest drivers, i have now tried release 3.14 with hip 6.1.2 and the rocm.gfx803.optic.vega10.logic.hip.sdk.6.1.2.
So the versions should match and yes i have changed the files in the directory (i only use the ollama.exe in the download of the release, i do not install the release at all)

What do you think should i try ? Should i try to use an old version and 5.7 ?  Can i provide any logs which would help to identify any issue ?


My exact steps:
download and install hip 6.1.2
download rocm.gfx803.optic.vega10.logic.hip.sdk.6.1.2.7z
replace the files in C:\Program Files\AMD\ROCm\6.1\bin\ 
`files in rocm.gfx803.optic.vega10.logic.hip.sdk.6.1.2.7z > C:\Program Files\AMD\ROCm\6.1\bin\ `

download the latest release (7zip) - extract
run ollama.exe from the downloaded release, replace the rocblas and library of the release with the ones from rocm.gfx803.optic.vega10.logic.hip.sdk.6.1.2.7z 
`files in rocm.gfx803.optic.vega10.logic.hip.sdk.6.1.2.7z > ollama-windows-amd64.7\ollama-windows-amd64\lib\ollama`


i have created a simple python script with logging, this is the log of the process:
```2024-10-25 20:55:09,606 - INFO - ======================================== Setup Start ========================================
2024-10-25 20:55:09,606 - INFO - Starting Ollama AMD setup process
2024-10-25 20:55:09,608 - INFO - File AMD-Software-PRO-Edition-24.Q3-Win10-Win11-For-HIP.exe already exists, skipping download
2024-10-25 20:55:09,616 - INFO - File rocm.gfx803.optic.vega10.logic.hip.sdk.6.1.2.7z already exists, skipping download
2024-10-25 20:55:09,616 - INFO - File ollama-windows-amd64.7z already exists, skipping download
2024-10-25 20:55:09,618 - INFO - Extracting rocm.gfx803.optic.vega10.logic.hip.sdk.6.1.2.7z to rocm_libs_extracted
2024-10-25 20:55:10,427 - INFO - Successfully extracted rocm.gfx803.optic.vega10.logic.hip.sdk.6.1.2.7z
2024-10-25 20:55:10,427 - INFO - Extracting ollama-windows-amd64.7z to ollama_extracted
2024-10-25 20:55:17,676 - INFO - Successfully extracted ollama-windows-amd64.7z
2024-10-25 20:55:17,676 - INFO - Starting AMD Software installation
2024-10-25 20:55:17,680 - INFO - Waiting for AMD Software installation to complete...
2024-10-25 20:55:17,680 - INFO - Please complete the installation process in the AMD Software installer window.
2024-10-25 20:56:33,588 - INFO - AMD Software installation confirmed complete
2024-10-25 20:56:33,588 - INFO - Copying rocblas.dll to destinations
2024-10-25 20:56:33,588 - INFO - ======================================== Copy Operation ========================================
2024-10-25 20:56:33,588 - INFO - Copying file from:
2024-10-25 20:56:33,588 - INFO - Source: C:\Users\user\Documents\ollama_amd_py\downloads\rocm_libs_extracted\rocblas.dll
2024-10-25 20:56:33,588 - INFO - To: C:\Users\user\Documents\ollama_amd_py\downloads\ollama_extracted\ollama-windows-amd64\lib\ollama\rocblas.dll
2024-10-25 20:56:33,588 - INFO - Removing existing file: C:\Users\user\Documents\ollama_amd_py\downloads\ollama_extracted\ollama-windows-amd64\lib\ollama\rocblas.dll
2024-10-25 20:56:33,625 - INFO - Copied file: rocblas.dll
2024-10-25 20:56:33,625 - INFO - Verifying copy:
2024-10-25 20:56:34,134 - INFO - --------------------------------------------------------------------------------
2024-10-25 20:56:34,134 - INFO - Hash Comparison:
2024-10-25 20:56:34,136 - INFO - Source path: C:\Users\user\Documents\ollama_amd_py\downloads\rocm_libs_extracted\rocblas.dll
2024-10-25 20:56:34,136 - INFO - Source hash: 2d24c8546c9ca04d3b50322b78ef4d88960757501644c1a022491a8be6432dba
2024-10-25 20:56:34,136 - INFO - Destination path: C:\Users\user\Documents\ollama_amd_py\downloads\ollama_extracted\ollama-windows-amd64\lib\ollama\rocblas.dll
2024-10-25 20:56:34,136 - INFO - Destination hash: 2d24c8546c9ca04d3b50322b78ef4d88960757501644c1a022491a8be6432dba
2024-10-25 20:56:34,136 - INFO - --------------------------------------------------------------------------------
2024-10-25 20:56:34,136 - INFO - Hash verification successful
2024-10-25 20:56:34,136 - INFO - ==========================================================================================
2024-10-25 20:56:34,136 - INFO - ======================================== Copy Operation ========================================
2024-10-25 20:56:34,136 - INFO - Copying file from:
2024-10-25 20:56:34,136 - INFO - Source: C:\Users\user\Documents\ollama_amd_py\downloads\rocm_libs_extracted\rocblas.dll
2024-10-25 20:56:34,136 - INFO - To: C:\Program Files\AMD\ROCm\6.1\bin\rocblas.dll
2024-10-25 20:56:34,137 - INFO - Removing existing file: C:\Program Files\AMD\ROCm\6.1\bin\rocblas.dll
2024-10-25 20:56:34,191 - INFO - Copied file: rocblas.dll
2024-10-25 20:56:34,191 - INFO - Verifying copy:
2024-10-25 20:56:34,444 - INFO - --------------------------------------------------------------------------------
2024-10-25 20:56:34,444 - INFO - Hash Comparison:
2024-10-25 20:56:34,447 - INFO - Source path: C:\Users\user\Documents\ollama_amd_py\downloads\rocm_libs_extracted\rocblas.dll
2024-10-25 20:56:34,447 - INFO - Source hash: 2d24c8546c9ca04d3b50322b78ef4d88960757501644c1a022491a8be6432dba
2024-10-25 20:56:34,447 - INFO - Destination path: C:\Program Files\AMD\ROCm\6.1\bin\rocblas.dll
2024-10-25 20:56:34,447 - INFO - Destination hash: 2d24c8546c9ca04d3b50322b78ef4d88960757501644c1a022491a8be6432dba
2024-10-25 20:56:34,447 - INFO - --------------------------------------------------------------------------------
2024-10-25 20:56:34,447 - INFO - Hash verification successful
2024-10-25 20:56:34,447 - INFO - ==========================================================================================
2024-10-25 20:56:34,447 - INFO - Copying library directory contents to destinations
2024-10-25 20:56:34,447 - INFO - ======================================== Copy Operation ========================================
2024-10-25 20:56:34,447 - INFO - Copying directory from:
2024-10-25 20:56:34,447 - INFO - Source: C:\Users\user\Documents\ollama_amd_py\downloads\rocm_libs_extracted\library
2024-10-25 20:56:34,447 - INFO - To: C:\Users\user\Documents\ollama_amd_py\downloads\ollama_extracted\ollama-windows-amd64\lib\ollama\rocblas\library
2024-10-25 20:56:34,447 - INFO - Clearing contents of directory: C:\Users\user\Documents\ollama_amd_py\downloads\ollama_extracted\ollama-windows-amd64\lib\ollama\rocblas\library
2024-10-25 20:56:34,449 - INFO - Removed file: C:\Users\user\Documents\ollama_amd_py\downloads\ollama_extracted\ollama-windows-amd64\lib\ollama\rocblas\library\Kernels.so-000-gfx1103.hsaco
2024-10-25 20:56:34,449 - INFO - Removed file: C:\Users\user\Documents\ollama_amd_py\downloads\ollama_extracted\ollama-windows-amd64\lib\ollama\rocblas\library\TensileLibrary_lazy_gfx1103.dat

2024-10-25 20:56:34,541 - INFO - Removed file: C:\Users\user\Documents\ollama_amd_py\downloads\ollama_extracted\ollama-windows-amd64\lib\ollama\rocblas\library\TensileLibrary_Type_ZZ_Contraction_l_Alik_Bljk_Cijk_Dijk_fallback_gfx1103.hsaco
2024-10-25 20:56:34,553 - INFO - Removed file: C:\Users\user\Documents\ollama_amd_py\downloads\ollama_extracted\ollama-windows-amd64\lib\ollama\rocblas\library\TensileManifest.txt
2024-10-25 20:56:34,555 - INFO - Copied file: Kernels.so-000-gfx803.hsaco
2024-10-25 20:56:34,555 - INFO - Copied file: TensileLibrary_lazy_gfx803.dat
2024-10-25 20:56:34,557 - INFO - Copied file: TensileLibrary_Type_4xi8I_HPA_Contraction_l_Ailk_Bjlk_Cijk_Dijk_fallback.dat
....
2024-10-25 20:56:34,711 - INFO - Copied file: TensileLibrary_Type_ZZ_Contraction_l_Alik_Bljk_Cijk_Dijk_gfx803.dat
2024-10-25 20:56:34,713 - INFO - Copied file: TensileManifest.txt
2024-10-25 20:56:34,713 - INFO - Verifying copy:
2024-10-25 20:56:36,002 - INFO - --------------------------------------------------------------------------------
2024-10-25 20:56:36,002 - INFO - Hash Comparison:
2024-10-25 20:56:36,004 - INFO - Source path: C:\Users\user\Documents\ollama_amd_py\downloads\rocm_libs_extracted\library
2024-10-25 20:56:36,004 - INFO - Source hash: 20d45da5dea3fe7e115d1043d152a37b78e674755b90b1aff7cf3a1939d32da7
2024-10-25 20:56:36,004 - INFO - Destination path: C:\Users\user\Documents\ollama_amd_py\downloads\ollama_extracted\ollama-windows-amd64\lib\ollama\rocblas\library
2024-10-25 20:56:36,004 - INFO - Destination hash: 20d45da5dea3fe7e115d1043d152a37b78e674755b90b1aff7cf3a1939d32da7
2024-10-25 20:56:36,004 - INFO - --------------------------------------------------------------------------------
2024-10-25 20:56:36,004 - INFO - Hash verification successful
2024-10-25 20:56:36,004 - INFO - ==========================================================================================
2024-10-25 20:56:36,004 - INFO - ======================================== Copy Operation ========================================
2024-10-25 20:56:36,004 - INFO - Copying directory from:
2024-10-25 20:56:36,004 - INFO - Source: C:\Users\user\Documents\ollama_amd_py\downloads\rocm_libs_extracted\library
2024-10-25 20:56:36,004 - INFO - To: C:\Program Files\AMD\ROCm\6.1\bin\rocblas\library
2024-10-25 20:56:36,004 - INFO - Clearing contents of directory: C:\Program Files\AMD\ROCm\6.1\bin\rocblas\library
2024-10-25 20:56:36,006 - INFO - Removed file: C:\Program Files\AMD\ROCm\6.1\bin\rocblas\library\Kernels.so-000-gfx1030.hsaco
.....
2024-10-25 20:56:36,318 - INFO - Removed file: C:\Program Files\AMD\ROCm\6.1\bin\rocblas\library\TensileLibrary_Type_ZZ_Contraction_l_Alik_Bljk_Cijk_Dijk_gfx906.dat
2024-10-25 20:56:36,332 - INFO - Removed file: C:\Program Files\AMD\ROCm\6.1\bin\rocblas\library\TensileManifest.txt
2024-10-25 20:56:36,332 - INFO - Copied file: Kernels.so-000-gfx803.hsaco
2024-10-25 20:56:36,334 - INFO - Copied file: TensileLibrary_lazy_gfx803.dat
2024-10-25 20:56:36,334 - INFO - Copied file: TensileLibrary_Type_4xi8I_HPA_Contraction_l_Ailk_Bjlk_Cijk_Dijk_fallback.dat
2024-10-25 20:56:36,336 - INFO - Copied file: TensileLibrary_Type_4xi8I_HPA_Contraction_l_Ailk_Bjlk_Cijk_Dijk_fallback_gfx803.hsaco
2024-10-25 20:56:36,336 - INFO - Copied file: TensileLibrary_Type_4xi8I_HPA_Contraction_l_Ailk_Bljk_Cijk_Dijk_fallback.dat
......
2024-10-25 20:56:36,465 - INFO - Copied file: TensileLibrary_Type_ZZ_Contraction_l_Alik_Bljk_Cijk_Dijk_gfx803.co
2024-10-25 20:56:36,465 - INFO - Copied file: TensileLibrary_Type_ZZ_Contraction_l_Alik_Bljk_Cijk_Dijk_gfx803.dat
2024-10-25 20:56:36,465 - INFO - Copied file: TensileManifest.txt
2024-10-25 20:56:36,465 - INFO - Verifying copy:
2024-10-25 20:56:37,059 - INFO - --------------------------------------------------------------------------------
2024-10-25 20:56:37,059 - INFO - Hash Comparison:
2024-10-25 20:56:37,061 - INFO - Source path: C:\Users\user\Documents\ollama_amd_py\downloads\rocm_libs_extracted\library
2024-10-25 20:56:37,061 - INFO - Source hash: 20d45da5dea3fe7e115d1043d152a37b78e674755b90b1aff7cf3a1939d32da7
2024-10-25 20:56:37,061 - INFO - Destination path: C:\Program Files\AMD\ROCm\6.1\bin\rocblas\library
2024-10-25 20:56:37,061 - INFO - Destination hash: 20d45da5dea3fe7e115d1043d152a37b78e674755b90b1aff7cf3a1939d32da7
2024-10-25 20:56:37,061 - INFO - --------------------------------------------------------------------------------
2024-10-25 20:56:37,061 - INFO - Hash verification successful
2024-10-25 20:56:37,061 - INFO - ==========================================================================================
2024-10-25 20:56:37,061 - INFO - ======================================== Setup Complete ========================================

PS C:\Users\user\Documents\ollama_amd_py\downloads\ollama_extracted\ollama-windows-amd64> .\ollama.exe serve
2024/10/25 21:05:11 routes.go:1170: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:C:\\Users\\user\\.ollama\\models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://*] OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-10-25T21:05:11.858+02:00 level=INFO source=images.go:754 msg="total blobs: 5"
time=2024-10-25T21:05:11.859+02:00 level=INFO source=images.go:761 msg="total unused blobs removed: 0"
time=2024-10-25T21:05:11.860+02:00 level=INFO source=routes.go:1217 msg="Listening on 127.0.0.1:11434 (version 0.3.14-0-gc692dfd)"
time=2024-10-25T21:05:11.861+02:00 level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[cpu_avx2 rocm_v6.1 cpu cpu_avx]"
time=2024-10-25T21:05:11.861+02:00 level=INFO source=gpu.go:221 msg="looking for compatible GPUs"
time=2024-10-25T21:05:11.861+02:00 level=INFO source=gpu_windows.go:167 msg=packages count=1
time=2024-10-25T21:05:11.861+02:00 level=INFO source=gpu_windows.go:214 msg="" package=0 cores=12 efficiency=0 threads=12
time=2024-10-25T21:05:11.868+02:00 level=INFO source=gpu.go:384 msg="no compatible GPUs were discovered"
time=2024-10-25T21:05:11.868+02:00 level=INFO source=types.go:123 msg="inference compute" id=0 library=cpu variant=avx2 compute="" driver=0.0 name="" total="39.1 GiB" available="33.5 GiB"```

**Comment by likelovewant** [comment]
`download rocm.gfx803.optic.vega10.logic.hip.sdk.6.1.2.7z
replace the files in C:\Program Files\AMD\ROCm\6.1\bin\
files in rocm.gfx803.optic.vega10.logic.hip.sdk.6.1.2.7z > C:\Program Files\AMD\ROCm\6.1\bin\ `
This steps only needed when you want to build your own ollama .
it's seems gfx803 no longer supported in ROCM6.1

Test [ollama-windows-amd64-rocm-5.7.7z](https://github.com/likelovewant/ollama-for-amd/releases/download/v0.3.11/ollama-windows-amd64-rocm-5.7.7z), with rocm5.7 , replace the libs with [ROCM5.7](https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/tag/v0.5.7) (try one of thems for gfx803 or test others) or test it with earlier version before [v0.3.6](https://github.com/likelovewant/ollama-for-amd/releases/tag/v0.3.6) with rocm5.7 support.

Once test it works, then can build ollama with rocm5.7 as guided  in wikis.

**Comment by zuli12-dev** [comment]
thanks i tried nearly every release with mostly every rocm5 library, i cannot get it to work at all. 
if the gpu is detected i only get error messages like this: 
```
ollama_llama_server.exe - Entry Point Not Found
The procedure entry point 'hipDeviceGetDefaultMemPool' was not found in the DLL 'C:\Users\mario\Downloads\version5-7\ollama-windows-amd64-3-5\rocm\rocblas.dll'.```

i am kind of lost now

**Comment by likelovewant** [comment]
Make sure you did not delete hipblas.dll file . or change the files location . only replace exsiting  `rocblas.dll` and `library `directory in the same directory in the 7z file .some old method for undetcted may helps https://github.com/likelovewant/ollama-for-amd/issues/18

**Comment by woodcoal** [comment]
我觉得根本原因是 hip 6.1.2 根本无法检测到 GPU。我的显卡在使用 6.1.2 编译的 Ollama 后提示检测不到显卡。不过如果你用之前 5.7 的版本可以检测到并运行。但是很不理想，还是思考需要一分钟，答案半天才蹦出来。

目前我找到最好的解决方案是基于 vulkan 的 llama.cpp 或者衍生软件。

尤其推荐 koboldcpp，运行 nocuda 的版本就可以了。
基本上畅通无阻，同样可以执行多模态的大模型。

象我们这些 AMD 老卡，再高端也迟早被抛弃，玩玩就算了，折腾的话，没有一个好爹都是废话。
到时候时间花了还一事无成。

**Comment by likelovewant** [comment]
> 我觉得根本原因是 hip 6.1.2 根本无法检测到 GPU。我的显卡在使用 6.1.2 编译的 Ollama 后提示检测不到显卡。不过如果你用之前 5.7 的版本可以检测到并运行。但是很不理想，还是思考需要一分钟，答案半天才蹦出来。
> 
> 目前我找到最好的解决方案是基于 vulkan 的 llama.cpp 或者衍生软件。
> 
> 尤其推荐 koboldcpp，运行 nocuda 的版本就可以了。 基本上畅通无阻，同样可以执行多模态的大模型。
> 
> 象我们这些 AMD 老卡，再高端也迟早被抛弃，玩玩就算了，折腾的话，没有一个好爹都是废话。 到时候时间花了还一事无成。

Sure ,it is . For some old cards, they are way slow , it has less meaning to further support it . AMD has remove lots of old cards data since rocm 6.0. According to the ollama , the rocmlibs direct work with drivers . it's means you do not need a hipsdk .  when the AMD remove the drivers support for hip6.1 .then it's impossible to make it work . if the cause from other reasons , rebuild the component may helps for those who only need to make a test or for a temporary use .

vulkan for llama.cpp and koboldcpp(nocuda) is always the options for those old cards.

**Comment by zuli12-dev** [comment]
i simply bought a new nvidia card so sadly i cannot test or help out here any further :(

**Comment by likelovewant** [comment]
> i simply bought a new nvidia card so sadly i cannot test or help out here any further :(

Nice, nvidia is better than any AMD so far in AI use. sure , no need to further info . Basicly the gfx803 and some old cards (gfx90c...) support untill rocm5.7 in windows . thanks for your sharing .

**Comment by ioshome2** [comment]
同样的问题，我还自己郁闷了好久。看起来是不支持了。

**Comment by likelovewant** [comment]
> 同样的问题，我还自己郁闷了好久。看起来是不支持了。

it's support with rocm5.7 , build yourself or checkout release package with rocm5.7
@ioshome2

**Comment by zuli12-dev** [comment]
I'll close this one as it is no problem anymore for me. Thanks for your help!
