### ISSUE TITLE
gfx1031 ollama_llama_server.exe-Entry Point Not Found *Error

### ISSUE THREAD

**Issue by washeree** [likelovewant/ollama-for-amd#27]
### What is the issue?

2024/11/09 15:37:24 routes.go:1189: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:C:\\Users\\xxx\\.ollama\\models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://*] OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-11-09T15:37:24.176+03:00 level=INFO source=images.go:755 msg="total blobs: 15"
time=2024-11-09T15:37:24.177+03:00 level=INFO source=images.go:762 msg="total unused blobs removed: 0"
time=2024-11-09T15:37:24.178+03:00 level=INFO source=routes.go:1240 msg="Listening on 127.0.0.1:11434 (version 0.4.1-1-g14a68a0)"
time=2024-11-09T15:37:24.179+03:00 level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[rocm cpu cpu_avx cpu_avx2]"
time=2024-11-09T15:37:24.179+03:00 level=INFO source=gpu.go:221 msg="looking for compatible GPUs"
time=2024-11-09T15:37:24.179+03:00 level=INFO source=gpu_windows.go:167 msg=packages count=1
time=2024-11-09T15:37:24.179+03:00 level=INFO source=gpu_windows.go:214 msg="" package=0 cores=12 efficiency=0 threads=24
time=2024-11-09T15:37:24.625+03:00 level=INFO source=types.go:123 msg="inference compute" id=0 library=rocm variant="" compute=gfx1031 driver=6.2 name="AMD Radeon RX 6700 XT" total="12.0 GiB" available="11.8 GiB"
[GIN] 2024/11/09 - 15:37:53 | 200 |      1.5666ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/11/09 - 15:37:53 | 200 |      1.2788ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/11/09 - 15:37:53 | 200 |      1.3169ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/11/09 - 15:37:53 | 200 |       168.2µs |       127.0.0.1 | GET      "/api/version"
[GIN] 2024/11/09 - 15:37:57 | 200 |       188.3µs |       127.0.0.1 | GET      "/api/version"
time=2024-11-09T15:38:01.025+03:00 level=INFO source=sched.go:185 msg="one or more GPUs detected that are unable to accurately report free memory - disabling default concurrency"
time=2024-11-09T15:38:01.060+03:00 level=INFO source=sched.go:714 msg="new model will fit in available VRAM in single GPU, loading" model=C:\Users\xxx\.ollama\models\blobs\sha256-2fb14853715210cc2015cd65f8ff6de5e597107327363e6dece4567d028a085a gpu=0 parallel=4 available=12571901952 required="6.5 GiB"
time=2024-11-09T15:38:01.486+03:00 level=INFO source=server.go:105 msg="system memory" total="31.9 GiB" free="21.8 GiB" free_swap="29.1 GiB"
time=2024-11-09T15:38:01.486+03:00 level=INFO source=memory.go:343 msg="offload to rocm" layers.requested=-1 layers.model=33 layers.offload=33 layers.split="" memory.available="[11.7 GiB]" memory.gpu_overhead="0 B" memory.required.full="6.5 GiB" memory.required.partial="6.5 GiB" memory.required.kv="1.0 GiB" memory.required.allocations="[6.5 GiB]" memory.weights.total="4.9 GiB" memory.weights.repeating="4.5 GiB" memory.weights.nonrepeating="411.0 MiB" memory.graph.full="560.0 MiB" memory.graph.partial="677.5 MiB"
time=2024-11-09T15:38:01.499+03:00 level=INFO source=server.go:383 msg="starting llama server" cmd="C:\\Users\\xxx\\AppData\\Local\\Programs\\Ollama\\lib\\ollama\\runners\\rocm\\ollama_llama_server.exe --model C:\\Users\\xxx\\.ollama\\models\\blobs\\sha256-2fb14853715210cc2015cd65f8ff6de5e597107327363e6dece4567d028a085a --ctx-size 8192 --batch-size 512 --n-gpu-layers 33 --threads 12 --parallel 4 --port 52622"
time=2024-11-09T15:38:01.506+03:00 level=INFO source=sched.go:449 msg="loaded runners" count=1
time=2024-11-09T15:38:01.506+03:00 level=INFO source=server.go:562 msg="waiting for llama runner to start responding"
time=2024-11-09T15:38:01.507+03:00 level=INFO source=server.go:596 msg="waiting for server to become available" status="llm server error"
time=2024-11-09T15:38:12.740+03:00 level=ERROR source=sched.go:455 msg="error loading llama server" error="llama runner process has terminated: exit status 0xc0000139"
[GIN] 2024/11/09 - 15:38:12 | 500 |    12.171969s |       127.0.0.1 | POST     "/api/chat"

Would you help to me with this please? I don't want to use docker. I tried to install RoCm and ollama many times and still same. I have 6700XT and as i know it's a gfx1031. Last 5-6hours i'm trying to make it work but i couldnt. Also i tried with Ollama-For-AMD-Installer, no luck at all. I would appreciate any help. Thank you. 

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.4.1 for amd version

**Comment by likelovewant** [comment]
This is due to the breaking change since v0.4.0 . The ROCmlibs need version v0.5.7 . if you replace libs with v0.6.1.2 ,you may came across this . also  Ollama-For-AMD-Installer only support rocmlibs for v0.6.2 . For now , please use rocmlibs for rocm5.7 . next release I will try build with rocm6.1.
@washeree

**Comment by washeree** [comment]
> This is due to the breaking change since v0.4.0 . The ROCmlibs need version v0.5.7 . if you replace libs with v0.6.1.2 ,you may came across this . also Ollama-For-AMD-Installer only support rocmlibs for v0.6.2 . For now , please use rocmlibs for rocm5.7 . next release I will try build with rocm6.1. @washeree

I forgot to say thanks a lot for your work. I will try now and keep you updated. After many installation as i remembered on v0.5.7 have problem to recognize my GPU but i can't be sure. Will post the result soon. Thanks again for your time.

**Comment by washeree** [comment]
Amazing its working now, i was facing a problem with python somehow. Thank you, closing the issue. @likelovewant
