### ISSUE TITLE
6700s not being detected

### ISSUE THREAD

**Issue by frabacc** [likelovewant/ollama-for-amd#30]
Hi, sorry to bother you again, but with the newest update what I did was (from scratch)
- I installed the OllamaSetup.exe file, version 0.4.1, from your repository.
- Replaced the files in the Ollama directory, rocblas.dll and the rocblas/library folder
- Installed the HIP SDK 5.7.1 and replaced the rocblas/library folder and the rocblas.dll
- Added and removed `HSA_OVERRIDE_GFX_VERSION=10.3.0` as a system enviroment variable 

This is the Ollama log
```
2024/11/13` 00:25:32 routes.go:1189: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION:10.3.0 HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:C:\\Users\\user\\.ollama\\models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://*] OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-11-13T00:25:32.295+01:00 level=INFO source=images.go:755 msg="total blobs: 0"
time=2024-11-13T00:25:32.295+01:00 level=INFO source=images.go:762 msg="total unused blobs removed: 0"
time=2024-11-13T00:25:32.295+01:00 level=INFO source=routes.go:1240 msg="Listening on 127.0.0.1:11434 (version 0.4.1-1-g14a68a0)"
time=2024-11-13T00:25:32.296+01:00 level=INFO source=common.go:49 msg="Dynamic LLM libraries" runners="[cpu cpu_avx cpu_avx2 rocm]"
time=2024-11-13T00:25:32.296+01:00 level=INFO source=gpu.go:221 msg="looking for compatible GPUs"
time=2024-11-13T00:25:32.296+01:00 level=INFO source=gpu_windows.go:167 msg=packages count=1
time=2024-11-13T00:25:32.296+01:00 level=INFO source=gpu_windows.go:214 msg="" package=0 cores=8 efficiency=0 threads=16
time=2024-11-13T00:25:32.304+01:00 level=INFO source=gpu.go:386 msg="no compatible GPUs were discovered"
time=2024-11-13T00:25:32.304+01:00 level=INFO source=types.go:123 msg="inference compute" id=0 library=cpu variant=avx2 compute="" driver=0.0 name="" total="15.2 GiB" available="10.5 GiB"
[GIN] 2024/11/13 - 00:29:43 | 200 |      1.0608ms |       127.0.0.1 | HEAD     "/"
```

_Originally posted by @frabacc in https://github.com/likelovewant/ollama-for-amd/issues/15#issuecomment-2471843204_

**Comment by frabacc** [comment]
FIXED IT! Incredibly, ROCm was not adding the `hipinfo` path to the Enviroment Variable, a simple fix was to add it to the Path!

**Comment by astranberg** [comment]
Can you pass clarify the steps you took and which gpu your using?  AMD RX 6700 XT or 6750?

And did you use gfx1031 or gfx1032

And hips 5.7 or 6.1.2?

Thanks!

**Comment by likelovewant** [comment]
both gfx1031,gfx1032  supports both in HIP 6.1.2 and 5.7 .

you can either get from [techpowerup](https://www.techpowerup.com/gpu-specs/) or install hipsdk ,add rocm/6.x or 5.x /bin into PATH . by run `hipinfo` get the info on windows.

or simply run something in ollama and it will shows some info   or post your ollama logs here .

**Comment by astranberg** [comment]
I got it to work! Re-reading the comment, I realized I needed to add `C:\Program Files\AMD\ROCm\6.1\bin\` to `Path`, not to its own System variable.

For anybody struggling get Ollama to work with an unsupported AMD card, here's what worked for my 6700 XT on Windows 11.
1. Clone the Ollama Repository: `git clone https://github.com/ollama/ollama.git`
2. Edit the Makefile.rocm, changing line 8 to `HIP_ARCHS_COMMON := gfx1031`
3. Installed [HIP SDK 6.1.2](https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html).
4. Assure you have a windows Environmental Variable named `HIP_PATH` set to `C:\Program Files\AMD\ROCm\6.1\`
5. Edit your windows Environmental Variable named `Path` to add `C:\Program Files\AMD\ROCm\6.1\bin\`
6. Downloaded the [ROCm files](https://github.com/likelovewant/ROCmLibs-for-gfx1103-AMD780M-APU/releases/download/v0.6.1.2/rocm.gfx1031.for.hip.sdk.6.1.2.optimized.with.little.wu.s.logic.7z) to make it work with my card.
- Copy `rocblas.dll` to `%HIP_PATH%\bin\` (replacing the file)
- Copy `library` folder to `%HIP_PATH%\bin\rocblas\` (replacing files)
7. Command into the Ollama folder. Run `make -j 9`.
8. Built the installer with `powershell -ExecutionPolicy Bypass -File .\scripts\build_windows.ps1` from the same folder.
9. Installed `OllamaSetup.exe` installer from the `Ollama\dist` folder.

The only downside is my `ollama --version` comes out as `ollama version is 0.5.6-2-g93a8daf-dirty`, and Ollama prompts me to update to `v0.5.6`. Any way around this?

**Comment by likelovewant** [comment]
Ignore it , or disable  it  ,by edit `[app/lifecycle/updater.go]`, change the url `https://ollama.com/api/update` to something else for fake it , like `https://ollama.com/api/update/1` . it will no longer prompts to update.

`ollama version is 0.5.6-2-g93a8daf-dirty` dirty is simply you are in dev mode .` git commit -m " message"` . the ` dirty is gone`
