### ISSUE TITLE
GPU is found,but can't run models(gfx906)

### ISSUE THREAD

**Issue by Glaceon-0471** [likelovewant/ollama-for-amd#48]
### What is the issue?

```
2025/02/05 00:45:17 routes.go:1259: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_KV_CACHE_TYPE: OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:C:\\Users\\la_sa\\.ollama\\models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://*] OLLAMA_SCHED_SPREAD:false ROCR_VISIBLE_DEVICES:]"
> time=2025-02-05T00:45:17.602+08:00 level=INFO source=images.go:757 msg="total blobs: 7"
> time=2025-02-05T00:45:17.603+08:00 level=INFO source=images.go:764 msg="total unused blobs removed: 0"
> time=2025-02-05T00:45:17.604+08:00 level=INFO source=routes.go:1310 msg="Listening on 127.0.0.1:11434 (version 0.5.4-1-g5c9deab)"
> time=2025-02-05T00:45:17.605+08:00 level=INFO source=routes.go:1339 msg="Dynamic LLM libraries" runners="[rocm_avx cpu cpu_avx cpu_avx2 rocm]"
> time=2025-02-05T00:45:17.605+08:00 level=INFO source=gpu.go:226 msg="looking for compatible GPUs"
> time=2025-02-05T00:45:17.605+08:00 level=INFO source=gpu_windows.go:167 msg=packages count=1
> time=2025-02-05T00:45:17.605+08:00 level=INFO source=gpu_windows.go:214 msg="" package=0 cores=6 efficiency=0 threads=12
> time=2025-02-05T00:45:18.308+08:00 level=INFO source=types.go:131 msg="inference compute" id=0 library=rocm variant="" compute=gfx906:sramecc-:xnack- driver=5.7 name="AMD Radeon VII" total="16.0 GiB" available="15.9 GiB"
```

I installed the Ollama environment according to the installation guide, and the GPU can be detected using `ollama serve` ,but when I tried to run a model (deepseek-r1:14b), the Ollama server didn't work and here is the log:

```
[GIN] 2025/02/05 - 00:51:31 | 200 |            0s |       127.0.0.1 | HEAD     "/"
[GIN] 2025/02/05 - 00:51:31 | 200 |     19.5254ms |       127.0.0.1 | POST     "/api/show"
time=2025-02-05T00:51:31.811+08:00 level=INFO source=sched.go:185 msg="one or more GPUs detected that are unable to accurately report free memory - disabling default concurrency"
time=2025-02-05T00:51:31.845+08:00 level=INFO source=sched.go:714 msg="new model will fit in available VRAM in single GPU, loading" model=C:\Users\la_sa\.ollama\models\blobs\sha256-aabd4debf0c8f08881923f2c25fc0fdeed24435271c2b3e92c4af36704040dbc gpu=0 parallel=4 available=17028874240 required="1.9 GiB"
time=2025-02-05T00:51:32.525+08:00 level=INFO source=server.go:104 msg="system memory" total="31.9 GiB" free="21.1 GiB" free_swap="22.7 GiB"
time=2025-02-05T00:51:32.525+08:00 level=INFO source=memory.go:356 msg="offload to rocm" layers.requested=-1 layers.model=29 layers.offload=29 layers.split="" memory.available="[15.9 GiB]" memory.gpu_overhead="0 B" memory.required.full="1.9 GiB" memory.required.partial="1.9 GiB" memory.required.kv="224.0 MiB" memory.required.allocations="[1.9 GiB]" memory.weights.total="976.1 MiB" memory.weights.repeating="793.5 MiB" memory.weights.nonrepeating="182.6 MiB" memory.graph.full="299.8 MiB" memory.graph.partial="482.3 MiB"
time=2025-02-05T00:51:32.534+08:00 level=INFO source=server.go:376 msg="starting llama server" cmd="C:\\Users\\la_sa\\AppData\\Local\\Programs\\Ollama\\lib\\ollama\\runners\\rocm\\ollama_llama_server.exe runner --model C:\\Users\\la_sa\\.ollama\\models\\blobs\\sha256-aabd4debf0c8f08881923f2c25fc0fdeed24435271c2b3e92c4af36704040dbc --ctx-size 8192 --batch-size 512 --n-gpu-layers 29 --threads 6 --parallel 4 --port 64865"
time=2025-02-05T00:51:33.286+08:00 level=INFO source=sched.go:449 msg="loaded runners" count=1
time=2025-02-05T00:51:33.286+08:00 level=INFO source=server.go:555 msg="waiting for llama runner to start responding"
time=2025-02-05T00:51:33.287+08:00 level=INFO source=server.go:589 msg="waiting for server to become available" status="llm server error"
time=2025-02-05T00:51:33.337+08:00 level=INFO source=runner.go:941 msg="starting go runner"
time=2025-02-05T00:51:33.352+08:00 level=INFO source=runner.go:942 msg=system info="AVX = 1 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 0 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | RISCV_VECT = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | cgo(gcc)" threads=12
time=2025-02-05T00:51:33.353+08:00 level=INFO source=.:0 msg="Server listening on 127.0.0.1:8080"
gguf_init_from_file: failed to open '': 'Invalid argument'
llama_model_load: error loading model: llama_model_loader: failed to load model from 

llama_load_model_from_file: failed to load model
panic: unable to load model: 

goroutine 6 [running]:
main.(*Server).loadModel(0xc000120120, {0x0, 0x0, 0x1, 0x0, {0x0, 0x0, 0x0}, 0xc0000221d0, 0x0}, ...)
	github.com/ollama/ollama/llama/runner/runner.go:863 +0x3ad
created by main.main in goroutine 1
	github.com/ollama/ollama/llama/runner/runner.go:975 +0xc6c
time=2025-02-05T00:51:33.538+08:00 level=ERROR source=sched.go:455 msg="error loading llama server" error="llama runner process has terminated: error loading model: llama_model_loader: failed to load model from"
```

Firstly I thought it was a problem like out of VRAM, then I tried a smaller model (deepseek-r1:1.5b), it gave the same error.

```
[GIN] 2025/02/05 - 00:53:35 | 200 |            0s |       127.0.0.1 | HEAD     "/"
[GIN] 2025/02/05 - 00:53:35 | 200 |     20.0961ms |       127.0.0.1 | POST     "/api/show"
time=2025-02-05T00:53:36.560+08:00 level=INFO source=sched.go:714 msg="new model will fit in available VRAM in single GPU, loading" model=C:\Users\la_sa\.ollama\models\blobs\sha256-6e9f90f02bb3b39b59e81916e8cfce9deb45aeaeb9a54a5be4414486b907dc1e gpu=0 parallel=4 available=17028874240 required="10.8 GiB"
time=2025-02-05T00:53:37.232+08:00 level=INFO source=server.go:104 msg="system memory" total="31.9 GiB" free="21.0 GiB" free_swap="22.4 GiB"
time=2025-02-05T00:53:37.233+08:00 level=INFO source=memory.go:356 msg="offload to rocm" layers.requested=-1 layers.model=49 layers.offload=49 layers.split="" memory.available="[15.9 GiB]" memory.gpu_overhead="0 B" memory.required.full="10.8 GiB" memory.required.partial="10.8 GiB" memory.required.kv="1.5 GiB" memory.required.allocations="[10.8 GiB]" memory.weights.total="8.9 GiB" memory.weights.repeating="8.3 GiB" memory.weights.nonrepeating="609.1 MiB" memory.graph.full="676.0 MiB" memory.graph.partial="916.1 MiB"
time=2025-02-05T00:53:37.238+08:00 level=INFO source=server.go:376 msg="starting llama server" cmd="C:\\Users\\la_sa\\AppData\\Local\\Programs\\Ollama\\lib\\ollama\\runners\\rocm\\ollama_llama_server.exe runner --model C:\\Users\\la_sa\\.ollama\\models\\blobs\\sha256-6e9f90f02bb3b39b59e81916e8cfce9deb45aeaeb9a54a5be4414486b907dc1e --ctx-size 8192 --batch-size 512 --n-gpu-layers 49 --threads 6 --parallel 4 --port 64914"
time=2025-02-05T00:53:37.320+08:00 level=INFO source=sched.go:449 msg="loaded runners" count=1
time=2025-02-05T00:53:37.320+08:00 level=INFO source=server.go:555 msg="waiting for llama runner to start responding"
time=2025-02-05T00:53:37.321+08:00 level=INFO source=server.go:589 msg="waiting for server to become available" status="llm server error"
time=2025-02-05T00:53:37.347+08:00 level=INFO source=runner.go:941 msg="starting go runner"
time=2025-02-05T00:53:37.359+08:00 level=INFO source=runner.go:942 msg=system info="AVX = 1 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 0 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 0 | FP16_VA = 0 | RISCV_VECT = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | cgo(gcc)" threads=12
time=2025-02-05T00:53:37.360+08:00 level=INFO source=.:0 msg="Server listening on 127.0.0.1:8080"
gguf_init_from_file: failed to open '': 'Invalid argument'
llama_model_load: error loading model: llama_model_loader: failed to load model from 

llama_load_model_from_file: failed to load model
panic: unable to load model: 

goroutine 19 [running]:
main.(*Server).loadModel(0xc0000dc120, {0x0, 0x0, 0x1, 0x0, {0x0, 0x0, 0x0}, 0xc00008a190, 0x0}, ...)
	github.com/ollama/ollama/llama/runner/runner.go:863 +0x3ad
created by main.main in goroutine 1
	github.com/ollama/ollama/llama/runner/runner.go:975 +0xc6c
time=2025-02-05T00:53:37.571+08:00 level=ERROR source=sched.go:455 msg="error loading llama server" error="llama runner process has terminated: error loading model: llama_model_loader: failed to load model from"
```

### OS

Windows

### GPU

AMD

### CPU

AMD

### Ollama version

0.5.4-1-g5c9deab

**Comment by likelovewant** [comment]
use default build ollamasetup.exe and rocm 6.1 libs. or maybe use the ollama official release . gfx906 support natively. Got report the gfx906 can works even with tags xnack- or others.

**Comment by Glaceon-0471** [comment]
> use default build ollamasetup.exe and rocm 6.1 libs. or maybe use the ollama official release . gfx906 support natively. Got report the gfx906 can works even with tags xnack- or others.

Great.I used default build and original rocm libs, then it works. Thx😉
