### ISSUE TITLE
amd 5700XT 用Ollama0.2.5后，启动不了任何大模型，换回ollamav0.1.48-alpha-2就正常

### ISSUE THREAD

**Issue by qixidao** [likelovewant/ollama-for-amd#7]
### What is the issue?

报错信息：rocBLAS error: Cannot read C:\Users\saki\AppData\Local\Programs\Ollama\rocm\/rocblas/library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1010
 List of available TensileLibrary Files : 
time=2024-07-19T10:47:59.810+08:00 level=ERROR source=sched.go:443 msg="error loading llama server" error="llama runner process has terminated: exit status 0xc0000409 error:Cannot read C:\\Users\\saki\\AppData\\Local\\Programs\\Ollama\\rocm\\/rocblas/library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1010"

这个是未加载模型前的日志，已经识别了5700xt为gfx1010:xnack- 
2024/07/19 10:58:34 routes.go:965: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION:9.0.12 OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_HOST:http://0.0.0.0:8080 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MAX_VRAM:0 OLLAMA_MODELS:D:\\300\\AMDROCm\\models OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[* http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://*] OLLAMA_RUNNERS_DIR:C:\\Users\\saki\\AppData\\Local\\Programs\\Ollama\\ollama_runners OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-07-19T10:58:34.993+08:00 level=INFO source=images.go:760 msg="total blobs: 35"
time=2024-07-19T10:58:34.995+08:00 level=INFO source=images.go:767 msg="total unused blobs removed: 0"
time=2024-07-19T10:58:34.997+08:00 level=INFO source=routes.go:1012 msg="Listening on [::]:8080 (version 0.2.5-0-gc7e2f88)"
time=2024-07-19T10:58:34.998+08:00 level=INFO source=payload.go:44 msg="Dynamic LLM libraries [cpu cpu_avx cpu_avx2 rocm_v5.7]"
time=2024-07-19T10:58:34.998+08:00 level=INFO source=gpu.go:205 msg="looking for compatible GPUs"
time=2024-07-19T10:58:35.054+08:00 level=INFO source=amd_windows.go:64 msg="skipping rocm gfx compatibility check" HSA_OVERRIDE_GFX_VERSION=9.0.12
time=2024-07-19T10:58:35.547+08:00 level=INFO source=types.go:105 msg="inference compute" id=0 library=rocm compute=gfx1010:xnack- driver=5.7 name="AMD Radeon RX 5700 XT" total="8.0 GiB" available="7.9 GiB"

### OS

Windows

### GPU

AMD

### CPU

Intel

### Ollama version

0.2.5

**Comment by likelovewant** [comment]
update v0.2.7 , 可以测试是否支持。之前如果移除 HSA_OVERRIDE_GFX_VERSION=9.0.12, gfx1010：xnack 是否无法正确识别。需要./llama serve 启动， 如果识别为gfx1010，可以测试 gfx1010的rocblibs. 当然我也可以把 gpu 支持改回 gfx1010 .

**Comment by qixidao** [comment]
> 更新 v0.2.7 ，可以测试是否支持。之前如果删除 HSA_OVERRIDE_GFX_VERSION=9.0.12, gfx1010：xnack 是否无法正确识别。./llamaserve 启动，需要识别为 gfx1010，可以测试 gfx1010 的 rocblibs。 当然我也可以把gpu支持改回gfx1010。@qixidao

好像和这些没啥关系，
我按照错误提示把对应文件TensileLibrary.dat和Kernels.so-000-gfx1010.hsaco
从C:\Program Files\AMD\ROCm\5.7\bin\rocblas\library复制到C:\Users\saki\AppData\Local\Programs\Ollama\rocm\rocblas\library
就能正常运行了

**Comment by likelovewant** [comment]
> > 更新 v0.2.7 ，可以测试是否支持。之前如果删除 HSA_OVERRIDE_GFX_VERSION=9.0.12, gfx1010：xnack 是否无法正确识别。./llamaserve 启动，需要识别为 gfx1010，可以测试 gfx1010 的 rocblibs。 当然我也可以把gpu支持改回gfx1010。@qixidao
> 
> 好像和这些没啥关系， 我按照错误提示把对应文件TensileLibrary.dat和Kernels.so-000-gfx1010.hsaco 从C:\Program Files\AMD\ROCm\5.7\bin\rocblas\library复制到C:\Users\saki\AppData\Local\Programs\Ollama\rocm\rocblas\library 就能正常运行了

第一个问题 ： 如果不设置HSA_OVERRIDE_GFX_VERSION=9.0.12 ，是否可以正常通过 ollama run llama3 启动？ 因为没有人反应过，有问题。不确定，想要确认一下。
第二： 每次更新安装都要替换ollama中 对应的rocblas.dll 和library 文件，（由于没有直接把这些文件编译进去，太大需要手动替换）这是方法。
第三：如果确认，第一个问题中提到的问题，需要额外设置HSA OVERRIDE ，则在未来版本中考虑配置 gfx1010 版本的roclibs 不而是gfx1010：xnack-，目前gfx1010版本的rocblas 不是优化版本的，可以编译优化版的（需要确认后编译）。 而gfx1010：xnack- 用的是优化版的。只是怀疑ollama 没有完全识别，所以你才要额外设置问题一中的问题。
没有其他。感谢反馈

**Comment by likelovewant** [comment]
since there is not update , the issue is reslove . I am gone close this .
